# Generated by Django 6.1 on 2026-08-14 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('ambito', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Bolsin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroBolsin', models.IntegerField(unique=True)),
                ('numeroPrecinto', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField()),
                ('peso', models.IntegerField(help_text='Peso en gramos')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsinesDestino', to='recepcion.comisionmedica')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsinesOrigen', to='recepcion.comisionmedica')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('asunto', models.CharField(max_length=250)),
                ('fechaPase', models.DateField()),
                ('cmOrigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentaciones', to='recepcion.comisionmedica')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcion.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(max_length=200)),
                ('tituloDocumento', models.CharField(blank=True, max_length=200)),
                ('documentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivoAdjunto', to='recepcion.documentacion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('asignadoA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='recepcion.comisionmedica')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recepcion.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='recepcion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstadoDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
                ('documentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambioEstado', to='recepcion.documentacion')),
                ('responsableCE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recepcion.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcion.estado')),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstadoBolsin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
                ('bolsin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambioEstado', to='recepcion.bolsin')),
                ('responsableCE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recepcion.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcion.estado')),
            ],
        ),
        migrations.AddField(
            model_name='comisionmedica',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recepcion.localidad'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcion.provincia'),
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('bolsin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remito', to='recepcion.bolsin')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remitosDestino', to='recepcion.comisionmedica')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcion.estado')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remitosOrigen', to='recepcion.comisionmedica')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCMCDestino', models.CharField(blank=True, max_length=150)),
                ('documentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcion.documentacion')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleRemito', to='recepcion.remito')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='recepcion.usuario')),
            ],
        ),
    ]
